import 'package:get/get.dart';

class LanguageUtil extends Translations {
  static Map<String, Map<String, String>> localData = {
    "en_IN": {
      "justTest": "Just Test",
      "Log in": "Log in",
      "Phone number": "Phone Number",
      "OTP Verification": "OTP Verification",
      "Request OTP": "Request OTP",
      "Enter the OTP you Received to": "Enter the OTP you Received to",
      "A 6 digit OTP will be sent via SMS to Verify your mobile number":
      "A 6 digit OTP will be sent via SMS to Verify your mobile number",
      "Submit": "Submit",
      "Resend OTP": "Resend OTP",
      "All Exams": "All Exams",
      "All": "All",
      "State Exams": "State Exams",
      "Categories": "Categories",
      "States & UTs": "States & UTs",
      "Search here": "Search here",
      "My Test": "My Test",
      "Report": "Report",
      "Calender": "Calender",
      "Live Test": "Live Test",
      "hr": "hr",
      "min": "min",
      "Speed:": "Speed:",
      "Incorrect:": "Incorrect:",
      "Correct": "Correct",
      "Support": "Support",
      "Suggested Test": "Suggested Test",
      "Popular Test Series": "Popular Test Series",
      "All Category": "All Category",
      "View all": "View All",
      "View test": "View Test",
      "Attempt": "Attempt",
      "Total": "Total",
      "Hin, Eng": "Hin, Eng",
      "Enrolled Test": "Enrolled Test",
      "Enrolled": "Enrolled",
      "Home": "Home",
      "Current Affairs": "Current Affairs",
      "Add Education": "Add Education",
      "Add Experience": "Add Experience",
      "Edit Education": "Edit Education",
      "Edit Experience": "Edit Experience",
      "View Report": "View Report",
      "Resume now": "Resume now",
      "hours/day": "hours/day",
      "Set your daily target to follow up, and achieve your goal.":
      "Set your daily target to follow up, and achieve your goal.",
      "Change daily goal": "Change daily goal",
      " vs last Month": " vs last Month",
      "My Wallet": "My Wallet",
      "Total test": "Total test",
      "Deposit": "Deposit",
      "Balance": "Balance",
      "Transaction History": "Transaction History",
      "Select your highest qualification": "Select your highest qualification",
      "Enter your mobile number": "Enter your mobile number",
      "s/Q": "s/Q",
      "See less": "See less",
      "See more": "See more",
      "This feature will be available soon.":
      "This feature will be available soon.",
      "General": "General",
      "OBC": "OBC",
      "SC": "SC",
      "ST": "ST",
      "EWS": "EWS",
      "Graduation": "Graduation",
      "Post Graduation": "Post Graduation",
      " from yesterday": " from yesterday",
      " vs yesterday": " vs yesterday",
      "Live Test Attempted": "Live Test Attempted",
      "Language": "Language",
      "English, Hindi, Marathi, Gujarati, Tamil, Telugu, Kannada, Malayalam":
      "English, हिंदी, मराठी, ગુજરાતી, தமிழ், తెలుగు, ಕನ್ನಡ, മലയാളം",
      "English": "English",
      "Hindi": "Hindi",
      "Marathi": "Marathi",
      "Gujarati": "Gujarati",
      "Tamil": "Tamil",
      "Telugu": "Telugu",
      "Kannada": "Kannada",
      "Malayalam": "Malayalam",
      "Bengali": "Bengali",
      "Punjabi": "Punjabi",
      "Last attempt test": "Last Attempt Test",
      "Banking": "Banking",
      "Test": "Test",
      "Free": "Free",
      "Hindi, English": "Hindi, English",
      "About": "About",
      "Start Now": "Start Now",
      "Show Details": "Show Details",
      "Add Your Details": "Add Your Details",
      "Platform": "Platform",
      "Link": "Link",
      "WhatsApp": "WhatsApp",
      "Contact Person": "Contact Person",
      "Save": "Save",
      "Exam start on": "Exam Start On",
      "Register now": "Register Now",
      "Affiliate program": "Affiliate Program",
      "Select date range": "Select Date Range",
      "Total refer": "Total Refer",
      "Test purchase": "Test Purchase",
      "Total Income": "Total Income",
      "Promote app": "Promote App",
      "Do you want to collaborate with us?":
      "Do you want to collaborate with us?",
      "Connect now": "Connect Now",
      "Enter your general details": "Enter Your General Details",
      "Full Name": "Full Name",
      "Your Name": "Your Name",
      "Email": "Email",
      "Mobile no.": "Mobile No.",
      "City": "City",
      "State": "State",
      "Enroll now": "Enroll now",
      "Attempted on": "Attempted On",
      "Download": "Download",
      "Title": "Title",
      "Add channel details": "Add Channel Details",
      "Channel Name": "Channel Name",
      "Important Instructions": "Important Instructions",
      "Choose your default language": "Choose your default language",
      "Select": "Select",
      "Please note all questions will appear in your default language. This language can be changed for a particular question later on.":
      "Please note all questions will appear in your default language. This language can be changed for a particular question later on.",
      "I have read and understood the instructions. All computer hardware allotted to me are in proper working condition. I declare that I am not in possession of / not wearing / not carrying any prohibited gadget like mobile phone, bluetooth devices etc. /any prohibited material with me into the Examination Hall.I agree that in case of not adhering to the instructions, I shall be liable to be debarred from this Test and/or to disciplinary action, which may include ban from future Tests / Examinations":
      "I have read and understood the instructions. All computer hardware allotted to me are in proper working condition. I declare that I am not in possession of / not wearing / not carrying any prohibited gadget like mobile phone, bluetooth devices etc. /any prohibited material with me into the Examination Hall.I agree that in case of not adhering to the instructions, I shall be liable to be debarred from this Test and/or to disciplinary action, which may include ban from future Tests / Examinations",
      "From (YYYY)": "From (YYYY)",
      "To (YYYY)": "To (YYYY)",
      "Select Degree": "Select Degree",
      "Job Title": "Job Title",
      "Company": "Company",
      "From": "From",
      "To": "To",
      "Currently working": "Currently working",
      "Select Employment Type": "Select Employment Type",
      "Update": "Update",
      "Become an educator": "Become An Educator",
      "Educator Status": "Educator Status",
      "Passionate about teaching kickstart your journey with us.":
      "Passionate about teaching, kickstart your journey with us.",
      "Age": "Age",
      "Qualification": "Qualification",
      "Set Your Daily Goal": "Set Your Daily Goal",
      "Exam want to test": "Exam Want To Test",
      "Upload paper": "Upload Paper",
      "Thank you!": "Thank You!",
      "We will contact you in 24-48 hours.":
      "We will contact you in 24-48 hours.",
      "Close": "Close",
      "Exam Information": "Exam Information",
      "Upcoming": "Upcoming",
      "Completed": "Completed",
      "Vacancy : ": "Vacancy : ",
      "Name of post": "Name Of Post",
      "Post Date": "Post Date",
      "Total Vacancy": "Total Vacancy",
      "Brief information": "Brief Information",
      "IMPORTANT DATES": "IMPORTANT DATES",
      "Last date for receipt of Applications : ":
      "Last date for receipt of Applications : ",
      "Age Limit": "Age Limit",
      "* Maximum Age for Manager & Team Leader : ":
      "Maximum Age for Manager & Team Leader : ",
      "* Maximum Age for Asst Manager & Officer : ":
      "Maximum Age for Asst Manager & Officer : ",
      "* Maximum Age for Marketing Executive : ":
      "Maximum Age for Marketing Executive : ",
      "Post name": "Post Name",
      "Interested Candidates can read the full notification before Apply":
      "Interested Candidates can read the full notification before Apply",
      "Important Links": "Important Links",
      "Click here": "Click Here",
      "Chapter test": "Chapter Test",
      "Chapter wise test": "Chapter Wise Test",
      "Sectional test": "Sectional Test",
      "Full test mini": "Full Test Mini",
      "Full test 100%": "Full Test 100%",
      "Live test mini": "Live Test Mini",
      "Live test full": "Live Test Full",
      "Prev. years papers": "Prev. Years Papers",
      "Ques.": "Ques.",
      "Marks": "Marks",
      "Min": "Min",
      "Apply Online": "Apply Online",
      "Notification": "Notification",
      "Official Website": "Official Website",
      "Buy Current Affairs Book (English Medium)":
      "Buy Current Affairs Book (English Medium)",
      "Current Affairs Attempted": "Current Affairs Attempted",
      "Download Mobile App": "Download Mobile App",
      "Join Telegram Channel": "Join Telegram Channel",
      "Profile": "Profile",
      "Select category": "Select category",
      "School/College/University": "School/College/University",
      "Department": "Department",
      "Grade": "Grade",
      "Select State": "Select State",
      "Select City": "Select City",
      "Select Language": "Select Language",
      "Education": "Education",
      "How it Works?": "How It Works?",
      "Ongoing": "Ongoing",
      "Resume Test": "Resume Test",
      "Vacancy Details": "Vacancy Details",
      "Start test": "Start Test",
      "Start Test": "Start Test",
      "Clear": "Clear",
      "Save & Next": "Save & Next",
      "Submit test": "Submit Test",
      "Attempted": "Attempted",
      "Marked": "Marked",
      "Unattempted": "Unattempted",
      "Unseen": "Unseen",
      "Time Left": "Time Left",
      "No": "No",
      "Yes": "Yes",
      "Analysis": "Analysis",
      "Solutions": "Solutions",
      "Rankers": "Rankers",
      "Time spent": "Time Spent",
      "Summary": "Summary",
      "Average Score": "Average Score",
      "Cut off": "Cut Off",
      "Rank": "Rank",
      "Score": "Score",
      "Percentile": "Percentile",
      "Compare": "Compare",
      "Time utilization": "Time Utilization",
      "Time spent on correctly attempted questions":
      "Time spent on correctly attempted questions",
      "Time spent on incorrectly questions":
      "Time spent on incorrectly questions",
      "Time spent on view but not answered questions":
      "Time spent on view but not answered questions",
      "Top 10 toppers comparison": "Top 10 toppers comparison",
      "Questions": "Questions",
      "Correct Answers is :": "Correct Answers Is :",
      "Solution": "Solution",
      "Hide Solution": "Hide Solution",
      "Previous": "Previous",
      "Next": "Next",
      "You": "You",
      "Time": "Time",
      "Accuracy:": "Accuracy:",
      "Accuracy": "Accuracy",
      "Q. Attem.": "Q. Attem.",
      "Live": "Live",
      "Complete": "Complete",
      "LIVE": "LIVE",
      "Result": "Result",
      "Reattempt": "Reattempt",
      "Slot ": "Slot ",
      "Unlock test": "Unlock Test",
      "User profile": "User Profile",
      "User Profile": "User Profile",
      "Refer & Earn": "Refer & Earn",
      "Affiliate Program": "Affiliate Program",
      "Raise a token for your issue": "Raise a token for your issue",
      "Which issue may we help you with?": "Which issue may we help you with?",
      "Please write the query": "Please write the query",
      "Write about your issue in detail": "Write about your issue in detail",
      "Write here": "Write here",
      "Become Educator": "Become Educator",
      "Become educator": "Become Educator",
      "Exam information": "Exam Information",
      "Preparation Calendar": "Preparation Calendar",
      "Daily Current affairs": "Daily Current affairs",
      "Dark Theme": "Dark Theme",
      "Logout": "Logout",
      "General Details": "General Details",
      "Mobile No.": "Mobile No.",
      "Email Address": "Email Address",
      "Date of Birth": "Date of Birth",
      "Select Your DOB": "Select Your DOB",
      "Category": "Category",
      "Pin Code": "Pin Code",
      "Experience": "Experience",
      "Invite friend and Businesses": "Invite friend And Businesses",
      "Copy the code share it with your friend":
      "Copy the code share it with your friend",
      "You have earned": "You Have Earned",
      "Your personal code": "Your Personal Code",
      "Copy": "Copy",
      "OR": "OR",
      "How it Work?": "How It Work?",
      "Share your referral code or link with your friends.":
      "Share your referral code or link with your friends.",
      "Are you sure you want to submit the test?":
      "Are you sure you want to submit the test?",
      "Friend sign-up with your link or referral code.":
      "Friend sign-up with your link or referral code.",
      "When your friend makes a purchase, you get upto 20% paytm cashback for Edepto Pass Pro purchase. Your friends too get 10% discount on any purchase of Edepto.":
      "When your friend makes a purchase, you get upto 20% paytm cashback for Edepto Pass Pro purchase. Your friends too get 10% discount on any purchase of Edepto.",
      "Time spent on goal": "Time Spent On Goal",
      "Total study hours": "Total Study Hours",
      " hrs in last week": " hrs in last week",
      "Test Attempted": "Test Attempted",
      "Practice Attempted": "Practice Attempted",
      "Current affairszes Attempted": "Current affairszes Attempted",
      "Total questions attempted": "Total Questions Attempted",
      " in last week": " in last week",
      "Strength & Weakness": "Strength & Weakness",
      "Attempt Rate": "Attempt Rate",
      "Live Current affairs": "Live Current affairs",
      "Recommended": "Recommended",
      "State Exam": "State Exam",
      "Your daily goal": "Your Daily Goal",
      "min/day": "min/day",
      "Change move goal": "Change Move Goal",
      "Mega Pass Offer": "Mega Pass Offer",
      "OFF": "OFF",
      "Validity": "Validity",
      "Valid till": "Valid till",
      "BUY NOW": "BUY NOW",
      "Offer Expires": "Offer Expires",
      "Exam Details": "Exam Details",
      "Select your Institute.": "Select your Institute.",
      "My Institute": "My Institute",
      "Institute Name": "Institute Name",
      "Location": "Location",
      "Hide Details": "Hide Details",
      "Description: Not available": "Description: Not available",
      "Mobile Number:": "Mobile Number:",
      "Email Id:": "Email Id:",
      "Website:": "Website:",
      "You don't have pass for the test series":
      "You don't have pass for the test series",
      'Select Institute': 'Select Institute',
      "Contact Institute": "Contact Institute",
      'Enter title': 'Enter title',
      'Description': 'Description',
      'Enter the description': 'Enter the description',
      "Please, write the title of your issue.":
      "Please, write the title of your issue.",
      "Please, write the description of your issue.":
      "Please, write the description of your issue.",
      "Course": "Course",
      "Dashboard": "Dashboard",
      "Hello": "Hello",
      'Current\nAffairs': 'Current\nAffairs',
      'Tips &\nTricks': 'Tips &\nTricks',
      'Videos &\nDocument': 'Videos &\nDocument',
      'Webinar': 'Webinar',
      'Job\nUpdates': 'Job\nUpdates',
      'Daily\nQuiz': 'Daily\nQuiz',
      'Quiz\nLeaderboard': 'Quiz\nLeaderboard',
      'Q&A And\nCommunity': 'Q&A And\nCommunity',
      "Course Details": "Course Details",
      "Available in": "Available in",
      "Total Test": "Total Test",
      "Mock Test": "Mock Test",
      "Study Materials": "Study Materials",
      'Video': 'Video',
      'PDF & Notes': 'PDF & Notes',
      'Tips & Tricks': 'Tips & Tricks',
      'Selected Course': 'Selected Course',
      "Sort By": "Sort By",
      'Apply': 'Apply',
      'Videos & Documents': 'Videos & Documents',
      "NEW": "NEW",
      "Already Registered": "Already Registered",
      "Register Now": "Register Now",
      'Job Notification': 'Job Notification',
      'Admit Card': 'Admit Card',
      'Results': 'Results',
      'Get Details': 'Get Details',
      "Vacancy": "Vacancy",
      "Daily Quiz": "Daily Quiz",
      "Question Count": "Question Count",
      "Total Points": "Total Points",
      "Quiz Duration": "Quiz Duration",
      "Pause and Exit": "Pause and Exit",
      "Confirm Exit": "Confirm Exit",
      "Submit Quiz": "Submit Quiz",
      "Time limit exceeds quiz auto submitted": "Time limit exceeds quiz auto submitted",
      "Quiz Score": "Quiz Score",
      "Congratulations!": "Congratulations!",
      "You’ve completed the quiz": "You’ve completed the quiz",
      "Quiz Results": "Quiz Results",
      "Questions Attempt": "Questions Attempt",
      "Go To Leaderboard": "Go To Leaderboard",
      "Back To Home": "Back To Home",
      "You are doing better than": "You are doing better than",
      "of the students!": "of the students!",
      "Community": "Community",
      "Have Any Question, Ask with professionals!": "Have Any Question, Ask with professionals!",
      "Ask Now": "Ask Now",
      "Question": "Question",
      "Write your question here...": "Write your question here...",
      "Select Tags": "Select Tags",
      "Discuss": "Discuss",
      "Day Ago": "Day Ago",
      "Hour Ago": "Hour Ago",
      "Post Answer": "Post Answer",
      "Post your answer, Write here...": "Post your answer, Write here...",
      'Chapter Test': 'Chapter Test',
      'Buy Pass': 'Buy Pass',
      "This test available from": "This test available from",
      "Resume Reattempt": "Resume Reattempt",
      'Pass': 'Pass',
      'Light Theme': 'Light Theme',
      "Update To Premium":  "Update To Premium",
      "Pass Applied": "Pass Applied",
      "Month": "Month",
      "Expires at": "Expires at",
      'Apply Coupon Code': 'Apply Coupon Code',
      "Subscribe Now": "Subscribe Now",
      'You\'ve earned': 'You\'ve earned',
      "Withdraw Now": "Withdraw Now",
      'Share With': 'Share With',
      "Refer & Earn Instantly!": "Refer & Earn Instantly!",
      "Share and get 10% in bank account after anyone of your referral register or enroll": "Share and get 10% in bank account after anyone of your referral register or enroll",
      "Pages": "Pages",
      'Your concern for us is always welcome, we will be thrilled by working with you!!': 'Your concern for us is always welcome, we will be thrilled by working with you!!',
      "Bank Details": "Bank Details",
      "Bank Account Number":"Bank Account Number",
      "Confirm Bank Account Number": "Confirm Bank Account Number",
      "IFSC Code": "IFSC Code",
      "Bank Name": "Bank Name",
      "Account Holder Name": "Account Holder Name",
      "Save & Verify": "Save & Verify",
      "Enter 6 Digit verification code share on your registered phone no.": "Enter 6 Digit verification code share on your registered phone no.",
      "Cancel": "Cancel",
      "Quiz Solution": "Quiz Solution",
      "View Solution": "View Solution",
      "View Score": "View Score",
      "Post": "Post",
      "Conducting Authority": "Conducting Authority",
      'This Week': 'This Week',
      'This Month': 'This Month',
      "Share": "Share",
      "Listening" : "Listening",
      "Ask With Voice": "Ask With Voice",
      "Submit Answer": "Submit Answer",
      "Oops!": "Oops!",
      "No Records Found": "No Records Found",
      "Our AI is generating answer": "Our AI is generating answer",
      "Do you want to exit the app": "Do you want to exit the app",
      "Exit": "Exit",
      "Refer code copied to clipboard": "Refer code copied to clipboard",
      "Please enter a valid Bank Account Number.": "Please enter a valid Bank Account Number.",
      "Please enter a valid Confirm Bank Account Number.": "Please enter a valid Confirm Bank Account Number.",
      "Bank Account Number and Confirm Bank Account Number is not same.": "Bank Account Number and Confirm Bank Account Number is not same.",
      "Please enter a valid IFSC Code.": "Please enter a valid IFSC Code.",
      "Please enter a valid Bank Name.": "Please enter a valid Bank Name.",
      "Please enter a valid Account Holder Name.": "Please enter a valid Account Holder Name.",
      "Enter all details": "Enter all details",
      'Enter your phone number': 'Enter your phone number',
      'Upload your sample question paper': 'Upload your sample question paper',
      "seconds": "seconds",
      "Resend OTP in" : "Resend OTP in",
      "SSC": "SSC",
      "Railway": "Railway",
      "Above answer is AI generated": "Above answer is AI generated",
      "Recently Posted": "Recently Posted",
      "Month Ago": "Month Ago",
      "Year Ago": "Year Ago",
      "Love Edepto": "Love Edepto",
      "Rate us your review will help us grow!": "Rate us your review will help us grow!",
      "Remind me later": "Remind me later",
    },
    "hi_IN": {
      "justTest": "बस परीक्षण",
      "Log in": "लॉग इन",
      "Phone number": "फ़ोन नंबर",
      "OTP Verification": "ओटीपी सत्यापन",
      "Request OTP": "ओटीपी का अनुरोध करें",
      "Enter the OTP you Received to": "आपको प्राप्त ओटीपी दर्ज करें",
      "A 6 digit OTP will be sent via SMS to Verify your mobile number":
      "आपके मोबाइल नंबर को सत्यापित करने के लिए एसएमएस के माध्यम से 6 अंकों का ओटीपी भेजा जाएगा",
      "Submit": "जमा करें",
      "Resend OTP": "ओटीपी पुनः भेजें",
      "All Exams": "सभी परीक्षाएं",
      "State Exams": "राज्य परीक्षाएं",
      "Categories": "श्रेणियाँ",
      "States & UTs": "राज्य और केंद्र शासित प्रदेश",
      "Search here": "यहाँ खोजें",
      "My Test": "मेरी परीक्षा",
      "Report": "रिपोर्ट",
      "Calender": "कैलेंडर",
      "Live Test": "लाइव परीक्षण",
      "hr": "घंटा",
      "min": "मिनट",
      "Speed:": "रफ़्तार:",
      "Incorrect:": "ग़लत:",
      "Select category": "श्रेणी चुनें",
      "School/College/University": "स्कूल/कॉलेज/विश्वविद्यालय",
      "Department": "विभाग",
      "Grade": "प्रतिशत ",
      "Select State": "राज्य चुनें",
      "Select City": "शहर चुनें",
      "Select Language": "भाषा चुने",
      "Education": "शिक्षण",
      "Educator Status": "शिक्षक स्थिति",
      "How it Works?": "यह किस प्रकार काम करता है?",
      "": "",
      "Ongoing": "जारी",
      "Support": "सहायता",
      "Suggested Test": "टेस्ट का सुझाव",
      "Popular Test Series": "प्रसिद्ध टेस्ट सीरीज",
      "All Category": "समस्त श्रेणी",
      "View all": "सभी को देखें",
      "View test": "परीक्षण देखें",
      "Attempt": "प्रयास",
      "Total": "कुल",
      "Hin, Eng": "हिं, अंग्रे",
      "Enrolled Test": "नामांकित टेस्ट",
      "Enrolled": "नामांकित",
      "Home": "होम",
      "Current Affairs": "करंट अफेयर्स",
      "Add Education": "शैक्षिक विवरण जोड़ें",
      "Add Experience": "अनुभव विवरण जोड़ें",
      "Edit Education": "शिक्षा संपादित करें",
      "Edit Experience": "अनुभव संपादित करें",
      "View Report": "परिणाम देखें",
      "Resume now": "अभी जारी करें",
      "hours/day": "घंटे/दिन",
      "Set your daily target to follow up, and achieve your goal.":
      "अनुसरण करने के लिए अपना दैनिक लक्ष्य निर्धारित करें, और अपना लक्ष्य प्राप्त करें।",
      "Change daily goal": "दैनिक लक्ष्य बदलें",
      " vs last Month": " पिछले महीने की तुलना में",
      "General": "सामान्य वर्ग",
      "OBC": "अन्य पिछड़ा वर्ग",
      "SC": "अनुसूचित जाति",
      "ST": "अनुसूचित जनजाति",
      "EWS": "आर्थिक रूप से कमज़ोर वर्ग",
      "Graduation": "स्नातक",
      "Post Graduation": "स्नातकोत्तर उपाधि",
      "My Wallet": "मेरा वोलेट",
      "Total test": "कुल परीक्षा",
      "Deposit": "जमा करें",
      "Balance": "बैलेंस",
      "Transaction History": "लेन-देन का हिसाब",
      "Select your highest qualification": "अपनी उच्चतम योग्यता चुनें",
      "Enter your mobile number": "अपना मोबाइल संख्या दर्ज करे",
      "s/Q": "से/प्र",
      " from yesterday": "कल से",
      " vs yesterday": "कल से",
      "Live Test Attempted": "लाइव टेस्ट का प्रयास",
      "Language": "भाषा",
      "English, Hindi, Marathi, Gujarati, Tamil, Telugu, Kannada, Malayalam":
      "English, हिंदी, मराठी, ગુજરાતી, தமிழ், తెలుగు, ಕನ್ನಡ, മലയാളം",
      "English": "English",
      "Add Your Details": "अपना विवरण जोड़ें",
      "Platform": "प्लैटफ़ॉर्म",
      "Link": "लिंक",
      "Set Your Daily Goal": "अपना दैनिक लक्ष्य निर्धारित करें",
      "WhatsApp": "व्हाट्सप्प",
      "Contact Person": "संपर्क व्यक्ति",
      "Save": "जमा करें",
      "Hindi": "हिंदी",
      "Marathi": "मराठी",
      "Gujarati": "ગુજરાતી",
      "Tamil": "தமிழ்",
      "Telugu": "తెలుగు",
      "Kannada": "ಕನ್ನಡ",
      "Malayalam": "മലയാളം",
      "Bengali": "বাংলা",
      "Punjabi": "ਪੰਜਾਬੀ",
      "Last attempt test": "पिछले परीक्षण",
      "Banking": "बैंकिंग",
      "Test": "परीक्षा",
      "Free": "मुक्त",
      "Hindi, English": "हिंदी, अंग्रेजी",
      "About": "बारे में",
      "Start Now": "शुरू करें",
      "Attempted on": "प्रयास का समय",
      "Download": "डाउनलोड",
      "Title": "शीर्षक",
      "Show Details": "विवरण देखें",
      "Exam start on": "परीक्षा का समय",
      "Register now": "पंजीकरण करें",
      "Affiliate program": "संबद्ध कार्यक्रम",
      "Raise a token for your issue": "अपने मुद्दे के लिए एक टोकन दर्ज करें",
      "Which issue may we help you with?":
      "हम किस मुद्दे पर आपकी मदद कर सकते हैं?",
      "Please write the query": "कृपया अपना प्रश्न लिखें",
      "Write about your issue in detail":
      "अपनी समस्या के बारे में विस्तार से लिखें",
      "Write here": "यहाँ लिखें",
      "Select date range": "दिनांक की सीमा चुनें",
      "Total refer": "कुल संदर्भ",
      "Test purchase": "परीक्षण खरीद",
      "Total Income": "कुल आय",
      "Promote app": "ऐप का प्रचार",
      "Do you want to collaborate with us?":
      "क्या आप हमारे साथ सहयोग करना चाहते हैं?",
      "Connect now": "अभी जुड़े",
      "Enter your general details": "अपना सामान्य विवरण दर्ज करें",
      "Full Name": "पूरा नाम",
      "Your Name": "आपका नाम",
      "Email": "ईमेल",
      "Mobile no.": "मोबाइल नं.",
      "City": "शहर",
      "State": "राज्य",
      "Add channel details": "चैनल विवरण जोड़ें",
      "Channel Name": "चैनल का नाम",
      "Important Instructions": "महत्वपूर्ण निर्देश",
      "Choose your default language": "अपनी भाषा का चयन करें",
      "Select": "चयन करें",
      "Please note all questions will appear in your default language. This language can be changed for a particular question later on.":
      "कृपया ध्यान दें कि सभी प्रश्न आपके चयन किये गए भाषा में दिखाई देंगे। इस भाषा को बाद में किसी विशेष प्रश्न के लिए बदला जा सकता है।",
      "I have read and understood the instructions. All computer hardware allotted to me are in proper working condition. I declare that I am not in possession of / not wearing / not carrying any prohibited gadget like mobile phone, bluetooth devices etc. /any prohibited material with me into the Examination Hall.I agree that in case of not adhering to the instructions, I shall be liable to be debarred from this Test and/or to disciplinary action, which may include ban from future Tests / Examinations":
      "मैंने अनुदेशों को पढ़ और समझ लिया है। मुझे आवंटित सभी कंप्यूटर हार्डवेयर उचित कार्यशील स्थिति में हैं। मैं घोषणा करता हूं कि परीक्षा हॉल में मेरे पास कोई भी प्रतिबंधित गैजेट जैसे मोबाइल फोन, ब्लूटूथ डिवाइस आदि / कोई भी निषिद्ध सामग्री नहीं है / मैं इसे अपने पास नहीं रखता / न पहनता / न ले जाता हूं। मैं सहमत हूं कि निर्देशों का पालन न करने की स्थिति में, मैं इस परीक्षा से वंचित किया जा सकता है और/या अनुशासनात्मक कार्रवाई की जा सकती है, जिसमें भविष्य की परीक्षा/परीक्षाओं से प्रतिबंध भी शामिल हो सकता है।",
      "Job Title": "नौकरी का नाम",
      "From (YYYY)": "प्रारंभ वर्ष",
      "To (YYYY)": "समाप्त वर्ष",
      "Select Degree": "डिग्री का चयन करें",
      "Company": "कंपनी",
      "From": "प्रारंभ वर्ष",
      "To": "समाप्त वर्ष",
      "Currently working": "वर्तमान में यहीं कार्यरत हैं",
      "Select Employment Type": "रोजगार का प्रकार चुनें",
      "Update": "अद्यतन करें",
      "Become an educator": "शिक्षक बनें",
      "Passionate about teaching kickstart your journey with us.": "पढ़ाने का जुनून है, हमारे साथ अपनी यात्रा शुरू करें।",
      "Age": "आयु",
      "Qualification": "शैक्षणिक योग्यता",
      "Exam want to test": "परीक्षा परीक्षण करना चाहते हैं",
      "Upload paper": "दस्तावेज़ अपलोड करें",
      "Thank you!": "धन्यवाद!",
      "We will contact you in 24-48 hours.":
      "हम 24-48 घंटों में आपसे संपर्क करेंगे.",
      "Close": "बंद करें",
      "See less": "कम देखें",
      "See more": "और देखें",
      "This feature will be available soon.": "यह सुविधा जल्द ही उपलब्ध होगी",
      "Exam Information": "परीक्षा की सूचना",
      "Upcoming": "आगामी",
      "Completed": "संपूर्ण",
      "Vacancy : ": "रिक्ति : ",
      "Name of post": "पद का नाम",
      "Post Date": "पोस्ट की तारीख",
      "Total Vacancy": "कुल रिक्ति",
      "Brief information": "संक्षिप्त जानकारी",
      "IMPORTANT DATES": "महत्वपूर्ण तिथियाँ",
      "Last date for receipt of Applications : ":
      "आवेदन प्राप्त करने की अंतिम तिथि:",
      "Age Limit": "आयु सीमा",
      "* Maximum Age for Manager & Team Leader : ":
      "प्रबंधक एवं टीम लीडर के लिए अधिकतम आयु : ",
      "* Maximum Age for Asst Manager & Officer : ":
      "सहायक प्रबंधक और अधिकारी के लिए अधिकतम आयु : ",
      "* Maximum Age for Marketing Executive : ":
      "मार्केटिंग एक्जीक्यूटिव के लिए अधिकतम आयु : ",
      "Vacancy Details": "रिक्ति का विवरण",
      "Post name": "पोस्ट नाम",
      "Interested Candidates can read the full notification before Apply":
      "इच्छुक उम्मीदवार आवेदन करने से पहले पूर्ण अधिसूचना पढ़ सकते हैं",
      "Important Links": "महत्वपूर्ण लिंक",
      "Click here": "क्लिक करें",
      "Chapter test": "अध्याय परीक्षण",
      "Chapter wise test": "अध्यायवार परीक्षण",
      "Sectional test": "अनुभागीय परीक्षण",
      "Full test mini": "छोटी पूर्ण परीक्षा",
      "Full test 100%": "पूर्ण परीक्षा 100%",
      "Live test mini": "छोटी लाइव परीक्षा",
      "Live test full": "पूरी लाइव परीक्षा",
      "Prev. years papers": "पिछले वर्षों के प्रश्न",
      "Ques.": "प्रश्न",
      "Marks": "अंक",
      "Min": "मिन",
      "Resume Test": "फिर से शुरू करें",
      "Start test": "परीक्षा आरंभ करें",
      "Start Test": "परीक्षा आरंभ करें",
      "Clear": "साफ़ करें",
      "Save & Next": "संचय और अगला",
      "Submit test": "परीक्षा जमा करें",
      "Attempted": "प्रयास किया हुआ",
      "Marked": "चिह्नित",
      "Unattempted": "अनायास",
      "Unattempted:": "अनायास:",
      "Topper": "टोपर",
      "Average": "औसत",
      "Unseen": "अपठित",
      "Time Left": "शेष समय",
      "No": "नहीं",
      "Yes": "हाँ",
      "Apply Online": "ऑनलाइन आवेदन",
      "Notification": "अधिसूचना",
      "Official Website": "आधिकारिक वेबसाइट",
      "Buy Current Affairs Book (English Medium)":
      "करेंट अफेयर्स की पुस्तक खरीदें (अंग्रेजी माध्यम)",
      "Current Affairs Attempted": "करंट अफेयर्स का प्रयास",
      "Download Mobile App": "मोबाइल ऐप डाउनलोड करें",
      "Join Telegram Channel": "टेलीग्राम चैनल से जुड़ें",
      "Profile": "प्रोफ़ाइल",
      "Analysis": "विश्लेषण",
      "Solutions": "समाधान",
      "Rankers": "रैंकर्स",
      "Time spent": "बिताया हुआ समय",
      "Summary": "सारांश",
      "Average Score": "औसत अंक:",
      "Cut off": "कट ऑफ़",
      "Rank": "क्रम",
      "Score": "अंक",
      "Percentile": "प्रतिशतता",
      "Correct": "सही:",
      "Correct:": "सही:",
      "Compare": "तुलना करें",
      "Time utilization": "समय का सदुपयोग",
      "Time spent on correctly attempted questions":
      "जो समय सही ढंग से हल किए गए प्रश्नों पर व्यतीत हुआ",
      "Time spent on incorrectly questions":
      "जो समय ग़लत ढंग से हल किए गए प्रश्नों पर व्यतीत हुआ",
      "Time spent on view but not answered questions":
      "उन प्रश्नों पर व्यतीत समय जिन्हें देखा गया लेकिन उत्तर नहीं दिया गया",
      "Top 10 toppers comparison": "शीर्ष 10 टॉपर्स की तुलना",
      "All": "सभी",
      "Questions": "प्रशन",
      "Correct Answers is :": "सही उत्तर है:",
      "Solution": "समाधान",
      "Hide Solution": "समाधान छिपाएँ",
      "Previous": "पिछला",
      "Next": "अगला",
      "You": "आप",
      "Time": "समय",
      "Accuracy:": "सटीकता:",
      "Accuracy": "सटीकता",
      "Q. Attem.": "प्रश्न प्रयास",
      "Live": "लाइव",
      "Complete": "पूर्ण",
      "Enroll now": "अभी नामांकन करें",
      "LIVE": "लाइव",
      "Result": "परिणाम",
      "Reattempt": "पुनः प्रयास",
      "Slot ": "स्लॉट ",
      "Unlock test": "अनलॉक परीक्षण",
      "User profile": "यूजर प्रोफ़ाइल",
      "User Profile": "यूजर प्रोफ़ाइल",
      "Refer & Earn": "रेफर करें और कमाएँ",
      "Affiliate Program": "संबद्ध कार्यक्रम",
      "Become Educator": "शिक्षक बनें",
      "Become educator": "शिक्षक बनें",
      "Exam information": "परीक्षा की जानकारी",
      "Preparation Calendar": "कैलेंडर की तैयारी",
      "Daily Current affairs": "दैनिक प्रश्नोत्तरी",
      "Dark Theme": "डार्क थीम",
      "Logout": "लॉग आउट",
      "General Details": "सामान्य विवरण",
      "Mobile No.": "मोबाइल न.",
      "Email Address": "ईमेल ",
      "Date of Birth": "जन्म तिथि",
      "Select Your DOB": "अपनी जन्मतिथि दर्ज करें",
      "Category": "वर्ग",
      "Pin Code": "पिन कोड",
      "Experience": "अनुभव",
      "Invite friend and Businesses": "मित्रों और व्यवसायों को आमंत्रित करें",
      "Copy the code share it with your friend":
      "कोड को कॉपी करें और अपने मित्र के साथ साझा करें",
      "You have earned": "आपने अर्जित किया",
      "Your personal code": "आपका व्यक्तिगत कोड",
      "Copy": "कापी",
      "OR": "या",
      "How it Work?": "यह कैसे कार्य करता है?",
      "Share your referral code or link with your friends.":
      "अपना रेफरल कोड या लिंक अपने दोस्तों के साथ साझा करें।",
      "Friend sign-up with your link or referral code.":
      "मित्र अपने लिंक या रेफरल कोड के साथ साइन-अप करें।",
      "Are you sure you want to submit the test?":
      "क्या आप परीक्षा जमा करना चाहते हैं?",
      "When your friend makes a purchase, you get upto 20% paytm cashback for Edepto Pass Pro purchase. Your friends too get 10% discount on any purchase of Edepto.":
      "जब आपका मित्र खरीदारी करता है, तो आपको एडेप्टो पास प्रो खरीदारी के लिए 20% तक पेटीएम कैशबैक मिलता है। आपके दोस्तों को भी एडेप्टो की किसी भी खरीदारी पर 10% की छूट मिलेगी।",
      "Time spent on goal": "लक्ष्य पर बिताया समय",
      "Total study hours": "अध्ययन के कुल  घंटे",
      " hrs in last week": " पिछले सप्ताह के कुल  घंट",
      "Test Attempted": "परीक्षण प्रयास",
      "Practice Attempted": "अभ्यास का प्रयास",
      "Current affairszes Attempted": "प्रश्नोत्तरी का प्रयास",
      "Total questions attempted": "कुल प्रयास किये गये प्रश्न",
      " in last week": " पिछले सप्ताह में",
      "Strength & Weakness": "ताकत और कमजोरियां",
      "Attempt Rate": "प्रयास दर",
      "Live Current affairs": "लाइव प्रश्नोत्तरी",
      "Recommended": "अनुशंसित",
      "State Exam": "राज्य परीक्षा",
      "Your daily goal": "आपका दैनिक लक्ष्य",
      "min/day": "मिनट/दिन",
      "Change move goal": "चाल लक्ष्य बदलें",
      "Mega Pass Offer": "मेगा पास ऑफर",
      "OFF": "की छूट",
      "Validity": "वैधता",
      "BUY NOW": "अभी खरीदें",
      "Offer Expires": "ऑफर की समाप्ति",
      "Exam Details": "परीक्षा विवरण",
      "Valid till": "वैध रहेगा",
      "Select your Institute.": "अपना संस्थान चुनें।",
      "My Institute": "मेरा संस्थान",
      "Institute Name": "संस्थान का नाम",
      "Location": "स्थान",
      "Hide Details": "विवरण छिपाएँ",
      "Description: Not available": "विवरण: उपलब्ध नहीं है",
      "Mobile Number:": "मोबाइल नंबर:",
      "Email Id:": "ईमेल आईडी:",
      "Website:": "वेबसाइट:",
      "You don't have pass for the test series":
      "आपके पास टेस्ट सीरीज़ के लिए पास नहीं है",
      'Select Institute': 'संस्थान बदलें',
      "Contact Institute": "संस्थान से संपर्क करें",
      'Enter title': 'शीर्षक दर्ज करें',
      'Description': 'विवरण',
      'Enter the description': 'विवरण दर्ज करें',
      "Please, write the title of your issue.":
      "कृपया, अपने समस्या का शीर्षक लिखें।",
      "Please, write the description of your issue.":
      "कृपया, अपनी समस्या का विवरण लिखें।",
      "Course": "कोर्स",
      "Dashboard": "डैशबोर्ड",
      "Hello": "नमस्ते",
      'Current\nAffairs': 'सामयिक\nघटनाएँ',
      'Tips &\nTricks': 'टिप्स एंड\nट्रिक्स',
      'Videos &\nDocument': 'वीडियो और\nदस्तावेज़',
      'Webinar': 'वेबिनार',
      'Job\nUpdates': 'नौकरी\nअद्यतन',
      'Daily\nQuiz': 'दैनिक\nप्रश्नोत्तरी',
      'Quiz\nLeaderboard': 'प्रश्नोत्तरी\nलीडरबोर्ड',
      'Q&A And\nCommunity': 'प्रश्नोत्तर और\nसमुदाय',
      "Course Details": "कोर्स विवरण",
      "Available in": "उपलब्ध भाषा",
      "Total Test": "कुल परीक्षा",
      "Mock Test": "मॉक टेस्ट",
      "Study Materials": "अध्ययन सामग्री",
      'Video': 'वीडियो',
      'PDF & Notes': 'पीडीएफ और नोट्स',
      'Tips & Tricks': 'टिप्स एंड ट्रिक्स',
      'Selected Course': 'चयनित कोर्स',
      "Sort By": "अनुसार क्रमबद्ध",
      'Apply': 'आवेदन करें',
      'Videos & Documents': 'वीडियो और दस्तावेज़',
      "NEW": "नया",
      "Already Registered": "पहले से पंजीकृत",
      "Register Now": "अभी पंजीकरण करें",
      'Job Notification': 'नौकरी अधिसूचना',
      'Admit Card': 'प्रवेश पत्र',
      'Results': 'परिणाम',
      'Get Details': 'विवरण प्राप्त करें',
      "Vacancy": "रिक्ति",
      "Daily Quiz": "दैनिक प्रश्नोत्तरी",
      "Question Count": "प्रश्न संख्या",
      "Total Points": "कुल अंक",
      "Quiz Duration": "प्रश्नोत्तरी अवधि",
      "Pause and Exit": "रोके और बाहर निकलें",
      "Confirm Exit": "बाहर निकलने की पुष्टि करें",
      "Submit Quiz": "प्रश्नोत्तरी जमा करें",
      "Time limit exceeds quiz auto submitted": "प्रश्नोत्तरी जमा करने की समय सीमा समाप्त हो गई है",
      "Quiz Score": "प्रश्नोत्तरी स्कोर",
      "Congratulations!": "बधाई हो!",
      "You’ve completed the quiz": "आपने प्रश्नोत्तरी पूरी कर ली है।",
      "Quiz Results": "प्रश्नोत्तरी परिणाम",
      "Questions Attempt": "प्रश्न प्रयास",
      "Go To Leaderboard": "लीडरबोर्ड पर जाएँ",
      "Back To Home": "होम में  वापस जाएं",
      "You are doing better than": "आप बेहतर कर रहे हैं",
      "of the students!": "छात्रों से!",
      "Community": "कम्युनिटी",
      "Have Any Question, Ask with professionals!": "कोई प्रश्न है, पेशेवरों से पूछें!",
      "Ask Now": "अभी पूछें",
      "Question": "प्रश्न",
      "Write your question here...": "अपना प्रश्न यहां लिखें...",
      "Select Tags": "टैग चुनें",
      "Discuss": "चर्चा करें",
      "Day Ago": "दिन पहले",
      "Hour Ago": "घंटा पहले",
      "Post Answer": "उत्तर पोस्ट करें",
      "Post your answer, Write here...": "अपना उत्तर पोस्ट करें, यहाँ लिखें...",
      'Chapter Test': 'अध्याय परीक्षा',
      'Buy Pass': 'पास खरीदें',
      "This test available from": "यह परीक्षा यहां से उपलब्ध है",
      "Resume Reattempt": "पुनः प्रयास जारी करें",
      'Pass': 'पास',
      'Light Theme': 'लाइट थीम',
      "Update To Premium":  "प्रीमियम में अद्यतन करें",
      "Pass Applied": "पास लागू",
      "Month": "महीना",
      "Expires at": "समाप्त होगा",
      'Apply Coupon Code': 'कूपन कोड लागू करें',
      "Subscribe Now": "अभी सदस्यता लें",
      'You\'ve earned': 'आपने कमाया है',
      "Withdraw Now": "अभी विथड्रॉ करें",
      'Share With': 'शेयर करें',
      "Refer & Earn Instantly!": "संदर्भ दें और तुरंत कमाएँ!",
      "Share and get 10% in bank account after anyone of your referral register or enroll": "आपके किसी भी रेफेरल रजिस्टर या नामांकन के बाद आपके खाते में 10% प्राप्त होगा।",
      "Pages": "पेज",
      'Your concern for us is always welcome, we will be thrilled by working with you!!': 'हमारे लिए आपकी चिंता का हमेशा स्वागत है, हम आपके साथ काम करके रोमांचित होंगे!!',
      "Bank Details": "बैंक विवरण",
      "Bank Account Number": "बैंक खाता संख्या",
      "Confirm Bank Account Number": "बैंक खाता संख्या की पुष्टि करें",
      "IFSC Code": "आईएफएससी कोड",
      "Bank Name": "बैंक का नाम",
      "Account Holder Name": "खाता धारक का नाम",
      "Save & Verify": "सहेजें और सत्यापित करें",
      "Enter 6 Digit verification code share on your registered phone no.": "अपने पंजीकृत फोन नंबर पर भेजे गये 6 अंकों का कोड दर्ज करें।",
      "Cancel": "रद्द करें",
      "Quiz Solution": "प्रश्नोत्तरी उत्तर",
      "View Solution": "उत्तर देखें",
      "View Score": "स्कोर देखें",
      "Post": "नियुक्ति",
      "Conducting Authority": "संचालन प्राधिकारी",
      'This Week': 'इस सप्ताह',
      'This Month': 'इस महीने',
      "Share": "शेयर करें",
      "Listening" : "सुन रहे हैं",
      "Ask With Voice": "आवाज़ देकर पूछें",
      "Submit Answer": "उत्तर जमा करें",
      "Oops!": "उफ़!",
      "No Records Found": "कोई तथ्य नहीं मिला",
      "Our AI is generating answer": "हमारा ए.आई. उत्तर प्रस्तुत कर रहा है",
      "Do you want to exit the app": "क्या आप ऐप से बाहर निकलना चाहते हैं",
      "Exit": "निकास",
      "Refer code copied to clipboard": "रेफेर कोड क्लिपबोर्ड पर कॉपी किया गया",
      "Please enter a valid Bank Account Number.": "कृपया एक वैध बैंक खाता संख्या दर्ज करें।",
      "Please enter a valid Confirm Bank Account Number.": "कृपया एक वैध पुष्टि बैंक खाता संख्या दर्ज करें।",
      "Bank Account Number and Confirm Bank Account Number is not same.": "बैंक खाता संख्या और पुष्टि बैंक खाता संख्या समान नहीं है।",
      "Please enter a valid IFSC Code.": "कृपया एक वैध आईएफएससी कोड दर्ज करें।",
      "Please enter a valid Bank Name.": "कृपया एक वैध बैंक नाम दर्ज करें।",
      "Please enter a valid Account Holder Name.": "कृपया एक वैध खाताधारक का नाम दर्ज करें।",
      "Enter all details": "सभी विवरण दर्ज करें",
      'Enter your phone number': 'अपना फोन नंबर दर्ज करें',
      'Upload your sample question paper': 'अपना नमूना प्रश्न पत्र अपलोड करें',
      "seconds": "सेकंड में",
      "Resend OTP in" : "ओटीपी पुनः भेजें",
      "SSC": "एसएससी",
      "Railway": "रेलवे",
      "Above answer is AI generated": "यह उत्तर ए.आई. द्वारा प्रस्तुत है।",
      "Recently Posted": "कुछ क्षण पहले",
      "Month Ago": "महीने पहले",
      "Year Ago": "साल पहले",
      "Love Edepto": "एडेप्टो पसंद आ रहा है",
      "Rate us your review will help us grow!": "हमें रेट करें आपकी समीक्षा हमें आगे बढ़ने में मदद करेगी!",
      "Remind me later": "मुझे बाद में याद दिलाना",
    }
  };
  @override
  Map<String, Map<String, String>> get keys => localData;

  // static init() async {
  //   var resp = await ApiCall.get(UrlApi.getLocal);
  //   if (resp["responseCode"] == 200) {
  //     Map<String, Map<String, String>> data = {};
  //     Map<String, dynamic> map = resp["data"];
  //     map.forEach((key, value) {
  //       data[key] = Map<String, String>.from(value);
  //     });
  //     localData = data;
  //   }
  //   return;
  // }
}
